services:
  - type: web
    name: stockstracker
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt && cd frontend-react && npm install && npm run build
    startCommand: python server.py
    autoDeploy: true
